import {
    createDefaultModule, createDefaultSharedModule, DefaultSharedModuleContext, inject,
    LangiumServices, LangiumSharedServices, Module, PartialLangiumServices
} from 'langium';
import { BricksGeneratedModule, BricksGeneratedSharedModule } from './generated/module';
import { BricksValidator, registerValidationChecks } from './bricks-validator';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type BricksAddedServices = {
    validation: {
        BricksValidator: BricksValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type BricksServices = LangiumServices & BricksAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const BricksModule: Module<BricksServices, PartialLangiumServices & BricksAddedServices> = {
    validation: {
        BricksValidator: () => new BricksValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createBricksServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Bricks: BricksServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        BricksGeneratedSharedModule
    );
    const Bricks = inject(
        createDefaultModule({ shared }),
        BricksGeneratedModule,
        BricksModule
    );
    shared.ServiceRegistry.register(Bricks);
    registerValidationChecks(Bricks);
    return { shared, Bricks };
}
